[package]
name = "bloodthorne"
version = "0.1.0"
authors = ["philippe gaultier <philigaultier@gmail.com>"]

[dependencies]
protobuf = "1.2.1"
snap = "0.2"
byteorder = "1.0"
log = "0.3.6"
regex = "0.2"
env_logger = "*"
bit-vec = "*"